[package]
name = "apl-scan"
description = "sw-apl token-level scanning: brackets, segments, del headers"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-ast = { path = "../apl-ast" }
apl-value = { path = "../../../value/crates/apl-value" }
apl-lex = { path = "../../../lex/crates/apl-lex" }

[lints]
workspace = true
