[package]
name = "apl-workspace"
description = "sw-apl active workspace: variables, environment, pending output"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-value = { path = "../../../value/crates/apl-value" }
apl-prims = { path = "../../../prims/crates/apl-prims" }

[lints]
workspace = true
