[package]
name = "apl-workspace"
description = "sw-apl active workspace: variables, functions, environment, output"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-ast = { path = "../../../parse/crates/apl-ast" }
apl-console = { path = "../apl-console" }
apl-clock = { path = "../apl-clock" }
apl-value = { path = "../../../value/crates/apl-value" }
apl-prims = { path = "../../../prims/crates/apl-prims" }
apl-space = { path = "../apl-space" }
apl-modes = { path = "../apl-modes" }
apl-store = { path = "../apl-store" }

[lints]
workspace = true
