[package]
name = "apl-display"
description = "sw-apl APL\\360-style output formatting"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-value = { path = "../../../value/crates/apl-value" }

[lints]
workspace = true
