[package]
name = "apl-eval"
description = "sw-apl evaluator and workspace"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-value = { path = "../../../value/crates/apl-value" }
apl-parse = { path = "../../../parse/crates/apl-parse" }
apl-prims-scalar = { path = "../../../prims/crates/apl-prims-scalar" }
apl-prims-mixed = { path = "../../../prims/crates/apl-prims-mixed" }
apl-prims-ops = { path = "../../../prims/crates/apl-prims-ops" }

[lints]
workspace = true
