[package]
name = "apl-eval"
description = "sw-apl evaluator and workspace"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-ast = { path = "../../../parse/crates/apl-ast" }
apl-call = { path = "../apl-call" }
apl-value = { path = "../../../value/crates/apl-value" }
apl-ibeam = { path = "../apl-ibeam" }
apl-parse = { path = "../../../parse/crates/apl-parse" }
apl-quad = { path = "../apl-quad" }
apl-prims = { path = "../../../prims/crates/apl-prims" }
apl-modes = { path = "../apl-modes" }
apl-store = { path = "../apl-store" }
apl-workspace = { path = "../apl-workspace" }

[dev-dependencies]
apl-call = { path = "../apl-call" }

[lints]
workspace = true
