⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (B)
⍝!SOURCE sw-apl -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 20.41.27 09/22/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 5
⍝!WIDTH 64
)WSID BIRDS
∇R←FG B X
⍝ FG IS 'F G', TWO FUNCTIONS BY NAME OR GLYPH: F G X.
R←⍎FG,' X'
∇
∇R←F C YZ
R←⍎'YZ[2] ',F,' YZ[1]'
∇
∇DESCRIBE
'BIRDS -- COMBINATORS, AFTER THE BIRDS OF SMULLYAN''S'
'TO MOCK A MOCKINGBIRD. HOWBIRDS SHOWS THEM ALL. A FUNCTION'
'IS GIVEN TO A BIRD BY NAME OR GLYPH, AS CHARACTERS, AND'
'EXECUTE CALLS IT: ANY FUNCTION, PRIMITIVE OR DEFINED.'
''
'   I X         IDIOT       X'
'   X K Y       KESTREL     X, IGNORING Y'
'   X KI Y      KITE        Y, IGNORING X: K GIVEN I'
'   X T F       THRUSH      F X'
'   FG B X      BLUEBIRD    F G X'
'   F C Y Z     CARDINAL    Z F Y'
'   F W X       WARBLER     X F X'
'   FG S X      STARLING    X F G X'
'   M F         MOCKINGBIRD F F'
'   F Y X       SAGE        THE FIXED POINT OF F, ON X'
''
'FG IS TWO FUNCTIONS, ''F G''. FSTEP, SHOUT AND HYP ARE THERE'
'TO BE GIVEN TO THE BIRDS. NOTHERE SAYS WHAT IS STILL MISSING.'
∇
∇R←FACT N
→(N>1)/MORE
R←1
→0
MORE:R←N×FACT N-1
∇
∇R←SELF FSTEP N
⍝ ONE STEP OF THE FACTORIAL. IT NEVER NAMES ITSELF: SELF IS HOW.
→(N>1)/MORE
R←1
→0
MORE:R←N×⍎SELF,' N-1'
∇
∇HOWBIRDS
'      I 42'
I 42
'      7 K 9'
7 K 9
'      7 KI 9'
7 KI 9
'      5 T ''⍳'''
5 T '⍳'
'      ''⌽ ⍳'' B 5'
'⌽ ⍳' B 5
'      ''FACT ⌈'' B 3.2'
'FACT ⌈' B 3.2
'      ''-'' C 10 3'
'-' C 10 3
'      ''HYP'' W 3'
'HYP' W 3
'      ''+ ⌽'' S ⍳5'
'+ ⌽' S ⍳5
'      M ''SHOUT'''
M 'SHOUT'
'      ''FSTEP'' Y 6'
'FSTEP' Y 6
∇
∇R←A HYP B
R←((A*2)+B*2)*0.5
∇
∇R←I X
R←X
∇
∇R←X K Y
R←X
∇
∇R←X KI Y
⍝ K GIVEN THE IDIOT: 'I' K X IS 'I', AND THAT NAME, APPLIED TO Y,
⍝ IS Y.
R←⍎('I' K X),' Y'
∇
∇R←M F
⍝ F APPLIED TO ITSELF: TO ITS OWN NAME.
R←⍎F,' F'
∇
∇NOTHERE
'WITH EXECUTE, EVERY BIRD THAT APL\360 COULD NOT WRITE IS HERE:'
'THE MOCKINGBIRD, THE SAGE, AND K GIVEN I. WHAT IS STILL'
'MISSING IS A FUNCTION AS A VALUE.'
''
'A BIRD IS GIVEN A FUNCTION''S NAME, AND GIVES BACK A VALUE. IT'
'CANNOT GIVE BACK A FUNCTION: B RETURNS F G X, NOT THE NEW'
'FUNCTION F G, AND K GIVEN A FUNCTION CAN ONLY HAND BACK ITS'
'NAME. NOR CAN A DEFINED FUNCTION BE AN OPERAND: / AND ∘. TAKE'
'PRIMITIVES ONLY, IN THIS APL AS IN APL\360.'
''
'Y HERE IS ALSO Z, ITS STRICT FORM: APL EVALUATES AN ARGUMENT'
'BEFORE IT CALLS, SO THE SAGE IT CAN WRITE IS THE STRICT ONE.'
∇
∇R←FG S X
⍝ FG IS 'F G': X F G X.
R←⍎'X ',FG,' X'
∇
∇R←SHOUT X
R←X,'!'
∇
∇R←X T F
R←⍎F,' X'
∇
∇R←F W X
R←⍎'X ',F,' X'
∇
∇R←F Y X;SELF
⍝ THE FIXED POINT OF F. F IS DYADIC: ITS LEFT ARGUMENT IS HOW TO
⍝ CALL ITSELF, AS CHARACTERS, SO IT RECURSES WITHOUT ITS OWN NAME.
SELF←'''',F,''' Y'
R←⍎'SELF ',F,' X'
∇
