⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)
⍝!SOURCE sw-apl -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 16.21.42 09/21/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 120
)WSID BIRDS
∇R←F APPLY X
⍝ THE MONADIC PRIMITIVE WHOSE GLYPH IS F, APPLIED TO X. APL\360
⍝ HAS NO EXECUTE, SO THE FUNCTIONS IT CAN REACH ARE THIS TABLE.
⍝ A GLYPH NOT IN IT IS AN INDEX ERROR.
→(NEG,REC,MAG,SGN,CEIL,FLR,IOTA,SHAPE,REV,RAV)['-÷|×⌈⌊⍳⍴⌽,'⍳F]
NEG:R←-X
→0
REC:R←÷X
→0
MAG:R←|X
→0
SGN:R←×X
→0
CEIL:R←⌈X
→0
FLR:R←⌊X
→0
IOTA:R←⍳X
→0
SHAPE:R←⍴X
→0
REV:R←⌽X
→0
RAV:R←,X
∇
∇R←FG B X
R←FG[1] APPLY FG[2] APPLY X
∇
∇R←F C YZ;FN
FN←F
R←YZ[2] DYAD YZ[1]
∇
∇DESCRIBE
'BIRDS -- THE COMBINATORS APL\360 CAN WRITE, AFTER THE BIRDS OF'
'SMULLYAN''S TO MOCK A MOCKINGBIRD. HOWBIRDS SHOWS THEM ALL.'
''
'ON VALUES, WHICH APL\360 CAN WRITE IN GENERAL:'
'   I X         IDIOT      X'
'   X K Y       KESTREL    X, IGNORING Y'
'   X KI Y      KITE       Y, IGNORING X'
''
'OVER A FIXED TABLE OF PRIMITIVES, EACH NAMED BY ITS GLYPH:'
'   X T F       THRUSH     F X'
'   FG B X      BLUEBIRD   F G X'
'   F C Y Z     CARDINAL   Z F Y'
'   F W X       WARBLER    X F X'
'   FG S X      STARLING   X F G X'
''
'   F APPLY X   THE MONADIC PRIMITIVE WHOSE GLYPH IS F, ON X'
'   X DYAD Y    X FN Y, FOR THE GLYPH IN THE CALLER''S FN'
''
'NOTHERE SAYS WHICH BIRDS ARE MISSING, AND WHY.'
∇
∇R←X DYAD Y
⍝ X FN Y, FOR THE GLYPH OF A DYADIC PRIMITIVE IN FN. FN IS NOT AN
⍝ ARGUMENT: IT IS A LOCAL OF THE CALLER, SEEN HERE BY DYNAMIC SCOPE,
⍝ WHICH IS HOW APL\360 PASSES WHAT IT HAS NO SYNTAX TO PASS.
→(PLUS,MINUS,TIMES,DIV,MAX,MIN,POW,RES,RHO,CAT,ROT,TAKE,DROP)['+-×÷⌈⌊*|⍴,⌽↑↓'⍳FN]
PLUS:R←X+Y
→0
MINUS:R←X-Y
→0
TIMES:R←X×Y
→0
DIV:R←X÷Y
→0
MAX:R←X⌈Y
→0
MIN:R←X⌊Y
→0
POW:R←X*Y
→0
RES:R←X|Y
→0
RHO:R←X⍴Y
→0
CAT:R←X,Y
→0
ROT:R←X⌽Y
→0
TAKE:R←X↑Y
→0
DROP:R←X↓Y
∇
∇R←FACT N
→(N>1)/MORE
R←1
→0
MORE:R←N×FACT N-1
∇
∇HOWBIRDS
'      I 42'
I 42
'      7 K 9'
7 K 9
'      7 KI 9'
7 KI 9
'      5 T ''⍳'''
5 T '⍳'
'      ''⌽⍳'' B 5'
'⌽⍳' B 5
'      ''-'' C 10 3'
'-' C 10 3
'      ''×'' W 5'
'×' W 5
'      ''⍴'' W 3'
'⍴' W 3
'      ''+⌽'' S ⍳5'
'+⌽' S ⍳5
'      FACT 6'
FACT 6
∇
∇R←I X
R←X
∇
∇R←X K Y
R←X
∇
∇R←X KI Y
R←Y
∇
∇NOTHERE
'M  MOCKINGBIRD. M X IS X X, A FUNCTION APPLIED TO ITSELF. THE'
'   FUNCTIONS HERE ARE NAMED BY A GLYPH, AND NO PRIMITIVE TAKES A'
'   GLYPH AS ITS ARGUMENT, SO THERE IS NO X X TO FORM.'
''
'Y  SAGE, AND Z, ITS STRICT FORM. EACH TAKES A FUNCTION AND GIVES'
'   BACK ITS FIXED POINT: RECURSION WITHOUT A NAME. APL\360 CANNOT'
'   GIVE ONE FUNCTION TO ANOTHER, NOR GIVE ONE BACK, SO NEITHER CAN'
'   BE WRITTEN. NOR IS EITHER NEEDED: A FUNCTION CALLS ITSELF BY'
'   NAME. FACT DOES, AND FACT 6 IS 720.'
''
'KI IS SMULLYAN''S K I, K GIVEN THE IDIOT. K CANNOT BE GIVEN A'
'   FUNCTION HERE, SO KI IS WRITTEN OUT INSTEAD.'
''
'AND T, B, C, W AND S REACH ONLY THE PRIMITIVES IN THE TABLES OF'
'APPLY AND DYAD. A DEFINED FUNCTION CANNOT BE NAMED TO THEM:'
'APL\360 HAS NO EXECUTE, SO A NAME IS ONLY CHARACTERS.'
∇
∇R←FG S X;FN
FN←FG[1]
R←X DYAD FG[2] APPLY X
∇
∇R←X T F
R←F APPLY X
∇
∇R←F W X;FN
FN←F
R←X DYAD X
∇
