⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!SOURCE sw-apl -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 22.53.10 09/17/26
⍝!LINK 16807
)WSID EDIT
)ORIGIN 1
)DIGITS 10
)WIDTH 120
∇DESCRIBE
'EDIT -- A WORKSPACE TO PRACTISE THE DEL EDITOR ON.'
''
'   FACT N     N FACTORIAL, BY A LOOP. IT IS WRONG BY ONE.'
'   MEAN X     THE MEAN OF A VECTOR. THIS ONE IS RIGHT.'
''
'FACT 5 SHOULD BE 120 AND IS NOT. OPEN IT, FIND THE LINE,'
'CHANGE IT, CLOSE IT. TYPE HOWEDIT FOR THE COMMANDS.'
∇
∇R←FACT N;I
R←1
I←1
LOOP:R←R×I
I←I+1
→LOOP×⍳I<N
∇
∇HOWEDIT
'OPEN A FUNCTION WITH A DEL AND ITS NAME, AND YOU ARE IN'
'DEFINITION MODE: THE PROMPT IS A LINE NUMBER IN BRACKETS.'
''
'   ∇FACT        REOPEN, AFTER THE LAST LINE'
'   [⎕]          DISPLAY THE WHOLE FUNCTION'
'   [4⎕]         DISPLAY FROM LINE 4 ON'
'   [4]          MOVE TO LINE 4'
'   [4] R←R×I    WRITE THAT AT LINE 4'
'   [4.1] TEXT   INSERT BETWEEN 4 AND 5'
'   [∆4]         DELETE LINE 4'
'   [0]          MOVE TO THE HEADER'
'   ∇            CLOSE, RENUMBERING FROM 1'
'   ⍫            CLOSE LOCKED, WHICH CANNOT BE UNDONE'
''
'A COMMAND MAY RIDE ON THE OPENING DEL: ∇FACT[⎕]∇ DISPLAYS'
'FACT AND LEAVES DEFINITION MODE AGAIN.'
∇
∇R←MEAN X
R←(+/X)÷⍴,X
∇
