⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 21.23.40 09/24/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 120
)WSID LEARN
∇DESCRIBE
'LEARN -- AN INTRODUCTION TO APL, FROM NOTHING.'
''
'   START      BEGIN: LESSON 1'
'   LESSON N   LESSON N, FROM 1 TO 9:'
''
'    1  WHERE YOU ARE          6  ERRORS'
'    2  NUMBERS                7  DEFINING A FUNCTION'
'    3  VECTORS                8  SAVING YOUR WORK'
'    4  REDUCTION, INDEXING    9  WHERE NEXT'
'    5  NAMES'
''
'EACH LESSON SHOWS A FEW LINES TO TRY, AND NAMES THE NEXT.'
'TAKE THEM AT YOUR OWN PACE; ANY ONE CAN BE SHOWN AGAIN.'
∇
∇LESSON N
→((1≠⍴,N)∨~∧/N∊1 2 3 4 5 6 7 8 9)/BAD
→((,N)=1 2 3 4 5 6 7 8 9)/A1,A2,A3,A4,A5,A6,A7,A8,A9
A1:∆L1
→0
A2:∆L2
→0
A3:∆L3
→0
A4:∆L4
→0
A5:∆L5
→0
A6:∆L6
→0
A7:∆L7
→0
A8:∆L8
→0
A9:∆L9
→0
BAD:'THE LESSONS ARE 1 TO 9.'
∇
∇START
LESSON 1
∇
∇∆L1
'LESSON 1: WHERE YOU ARE'
''
'THE SIX SPACES BEFORE WHAT YOU TYPE ARE THE PROMPT: APL IS'
'WAITING FOR A LINE. A LINE THAT BEGINS WITH ) IS A SYSTEM'
'COMMAND, WHICH ASKS THE SYSTEM AROUND APL FOR SOMETHING'
'RATHER THAN COMPUTING. TRY THESE:'
''
'      )DIALECT     WHICH MODE THIS SESSION IS IN'
'      )WSID        THE ACTIVE WORKSPACE''S NAME: LEARN'
'      )LIBS        THE LIBRARIES YOU CAN REACH'
'      )LIB 1       THE WORKSPACES IN LIBRARY 1'
'      )HELP        THE COMMANDS, AND HOW TO ASK ABOUT ONE'
''
'A WORKSPACE HOLDS VARIABLES AND FUNCTIONS. THIS ONE IS LEARN:'
')LOAD BROUGHT IT IN, AND IT STAYS UNTIL ANOTHER REPLACES IT.'
''
'TYPE LESSON 2 FOR NUMBERS.'
∇
∇∆L2
'LESSON 2: NUMBERS'
''
'TYPE AN EXPRESSION AND APL SHOWS ITS VALUE:'
''
'      2+3'
'      7-10         ANSWERS ¯3'
'      4×5          TIMES IS ×, NOT *'
'      1÷4          DIVIDE IS ÷, NOT /'
''
'A NEGATIVE NUMBER IS WRITTEN WITH THE HIGH MINUS, ¯, WHICH'
'IS PART OF THE NUMBER. - IS A FUNCTION: SUBTRACT, OR NEGATE.'
''
'THERE IS NO PRECEDENCE. A FUNCTION TAKES AS ITS RIGHT'
'ARGUMENT THE VALUE OF EVERYTHING TO ITS RIGHT, SO A LINE IS'
'READ FROM THE RIGHT, AND PARENTHESES GROUP AS USUAL:'
''
'      2×3+4        2×(3+4), WHICH IS 14'
'      (2×3)+4      10'
''
'WITH NOTHING ON ITS LEFT, A FUNCTION TAKES ONE ARGUMENT:'
''
'      -5           NEGATE'
'      ÷4           RECIPROCAL'
'      ⌈2.5         CEILING; ⌊ IS FLOOR'
''
'TYPE LESSON 3 FOR VECTORS.'
∇
∇∆L3
'LESSON 3: VECTORS'
''
'NUMBERS WRITTEN SIDE BY SIDE ARE ONE VALUE, A VECTOR, AND'
'ARITHMETIC WORKS ON EVERY ELEMENT AT ONCE:'
''
'      1 2 3+10 20 30'
'      2×1 2 3      ONE NUMBER GOES WITH EVERY ELEMENT'
'      ⍳5           THE FIRST FIVE WHOLE NUMBERS'
'      ⍴3 1 4 1 5   SHAPE: HOW MANY ELEMENTS'
''
'WITH A LEFT ARGUMENT, ⍴ RESHAPES:'
''
'      2 3⍴⍳6       TWO ROWS OF THREE: A MATRIX'
'      5⍴0          FIVE ZEROS'
''
'TEXT IS A VECTOR OF CHARACTERS, BETWEEN QUOTES:'
''
'      ''HELLO'''
'      ⍴''HELLO'''
''
'VECTORS OF DIFFERENT LENGTHS DO NOT ADD: 1 2+1 2 3 IS A'
'LENGTH ERROR. LESSON 6 IS ABOUT ERRORS.'
''
'TYPE LESSON 4 FOR REDUCTION AND INDEXING.'
∇
∇∆L4
'LESSON 4: REDUCTION AND INDEXING'
''
'A FUNCTION FOLLOWED BY / GOES BETWEEN EVERY PAIR OF'
'ELEMENTS, WHICH IS CALLED REDUCTION:'
''
'      +/1 2 3 4    1+2+3+4, THE SUM'
'      ×/⍳5         THE PRODUCT'
'      ⌈/3 1 4 1 5  THE LARGEST'
''
'BRACKETS PICK ELEMENTS BY POSITION, COUNTING FROM 1:'
''
'      V←10 20 30 40'
'      V[2]'
'      V[4 1]'
''
'AND A FEW MORE FUNCTIONS TO TRY ON V:'
''
'      ⌽V           REVERSE'
'      2↑V          TAKE THE FIRST TWO; ↓ DROPS THEM'
'      V⍳30         WHERE 30 IS'
'      +/V>15       HOW MANY ARE OVER 15'
''
'TYPE LESSON 5 FOR NAMES.'
∇
∇∆L5
'LESSON 5: NAMES'
''
'← GIVES A VALUE A NAME. ASSIGNING SHOWS NOTHING; THE NAME'
'ALONE SHOWS WHAT IT HOLDS:'
''
'      PRICE←3 5 2'
'      QTY←10 4 7'
'      PRICE×QTY'
'      TOTAL←+/PRICE×QTY'
'      TOTAL'
''
'A NAME IS A LETTER FOLLOWED BY LETTERS AND DIGITS. ASSIGN'
'TO IT AGAIN TO CHANGE IT. TWO COMMANDS LOOK AFTER NAMES:'
''
'      )VARS        LIST THE VARIABLES'
'      )ERASE QTY   FORGET ONE'
''
'A NAME THAT HOLDS NOTHING IS A VALUE ERROR.'
''
'TYPE LESSON 6 FOR ERRORS.'
∇
∇∆L6
'LESSON 6: ERRORS'
''
'WHEN APL CANNOT DO WHAT A LINE ASKS, IT SAYS WHAT WENT'
'WRONG, SHOWS THE LINE, AND PUTS A CARET UNDER THE PLACE IT'
'STOPPED. NOTHING THE LINE ASKED FOR IS DONE. TRY:'
''
'      1 2+1 2 3'
''
'THEN TYPE THE LINE AGAIN, CORRECTED. THE COMMON ONES:'
''
'   SYNTAX ERROR   NOT A SENTENCE           2+'
'   VALUE ERROR    A NAME WITH NO VALUE     NOSUCH'
'   DOMAIN ERROR   NOT FOR THIS VALUE       1÷0'
'   LENGTH ERROR   LENGTHS DIFFER           1 2+1 2 3'
'   RANK ERROR     SHAPES DO NOT FIT        (2 2⍴1)+1 2'
'   INDEX ERROR    NO SUCH POSITION         (1 2 3)[4]'
''
'TYPE LESSON 7 FOR DEFINING A FUNCTION.'
∇
∇∆L7
'LESSON 7: DEFINING A FUNCTION'
''
'THE DEL, ∇, OPENS A DEFINITION. THE HEADER NAMES THE RESULT,'
'THE FUNCTION AND ITS ARGUMENT. APL PROMPTS WITH LINE NUMBERS,'
'AND A SECOND DEL CLOSES IT:'
''
'      ∇R←AVG X'
'[1]   R←(+/X)÷⍴X'
'[2]   ∇'
'      AVG 3 5 10'
''
'NAMES AFTER A SEMICOLON IN THE HEADER, AS IN ∇R←AVG X;N, ARE'
'LOCAL: THEY EXIST ONLY WHILE THE FUNCTION RUNS.'
''
'      )FNS         THE FUNCTIONS: YOURS, AND LEARN''S'
''
'A FUNCTION THAT FAILS STOPS AND WAITS, SUSPENDED, SO YOU CAN'
'LOOK AT ITS NAMES. )SI SHOWS WHERE IT STOPPED, AND A RIGHT'
'ARROW ALONE, →, CLEARS IT.'
''
'TYPE LESSON 8 FOR SAVING YOUR WORK.'
∇
∇∆L8
'LESSON 8: SAVING YOUR WORK'
''
'THE ACTIVE WORKSPACE IS GONE WHEN THE SESSION ENDS, UNLESS'
'YOU SAVE IT. LIBRARY 0 IS YOURS:'
''
'      )WSID MINE   NAME THE WORKSPACE'
'      )SAVE        KEEP IT IN LIBRARY 0'
'      )LIB         LIST LIBRARY 0'
'      )CLEAR       START AGAIN, WITH NOTHING'
'      )LOAD MINE   BRING IT BACK'
''
'LIBRARY 1 IS WHAT SW-APL SHIPS, AND IS NOT SAVED TO:'
''
'      )LOAD 1 LIFE   A WORKSPACE TO EXPLORE; TYPE DESCRIBE'
''
')LOAD REPLACES THE ACTIVE WORKSPACE, THIS ONE INCLUDED, AND'
')LOAD 1 LEARN BRINGS THE LESSONS BACK.'
''
'TYPE LESSON 9 FOR WHERE TO GO NEXT.'
∇
∇∆L9
'LESSON 9: WHERE NEXT'
''
'SW-APL HAS TWO MODES, AND )DIALECT SAYS WHICH IS YOURS:'
''
'   (A) ''70  THE APL OF 1970. I-BEAMS READ SYSTEM VALUES,'
'            AND )ORIGIN, )DIGITS AND )WIDTH SET THE SETTINGS.'
'   (B) ''75  THE APL OF A 1975 DESKTOP COMPUTER. EXECUTE ⍎,'
'            FORMAT ⍕, AND QUAD SYSTEM VARIABLES SUCH AS ⎕IO;'
'            NO I-BEAMS.'
''
')HELP MODES SAYS MORE. THE DESKTOP MACHINE (B) IS MODELLED'
'ON HAD NO CLOCK, SO IN (B) THE DATE IN ⎕TS IS IN 1900.'
''
'MORE WORKSPACES MAY BE REACHED BEYOND LIBRARY 1; )LIBS LISTS'
'THEM. WHERE LIBRARY 2 IS THERE, )LIB 2 LISTS WHAT IT HOLDS:'
'A LONGER COURSE, DRILLS, AND MORE.'
''
')HELP LISTS EVERY COMMAND. THAT IS THE LAST LESSON.'
∇
