⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 22.52.29 09/17/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 120
)WSID LIFE
BOARD←6 6⍴0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
∇DESCRIBE
'LIFE -- CONWAY''S GAME OF LIFE ON A TORUS.'
''
'   GEN B      ONE GENERATION OF THE BOOLEAN MATRIX B.'
'   RUN N      STEP THE VARIABLE BOARD N GENERATIONS, SHOWING EACH.'
'   BOARD      A 6 BY 6 BOARD HOLDING A GLIDER.'
'   GLIDER     PUT THE GLIDER BACK ON AN EMPTY BOARD.'
''
'TYPE HOWRUN FOR MORE. THE EDGES WRAP: THE BOARD IS A TORUS.'
∇
∇R←GEN B;N
N←(¯1⊖¯1⌽B)+(¯1⊖B)+(¯1⊖1⌽B)+(¯1⌽B)+(1⌽B)+(1⊖¯1⌽B)+(1⊖B)+(1⊖1⌽B)
R←(3=N)∨B∧2=N
∇
∇GLIDER
BOARD←6 6⍴0
BOARD[1;2]←1
BOARD[2;3]←1
BOARD[3;1 2 3]←1
∇
∇HOWRUN
'GLIDER SETS BOARD UP AND RUN 4 STEPS IT FOUR GENERATIONS:'
''
'      GLIDER'
'      RUN 4'
''
'AFTER FOUR GENERATIONS A GLIDER HAS MOVED ONE CELL DOWN AND'
'ONE RIGHT. GEN IS AN ORDINARY FUNCTION, SO ONE GENERATION IS'
'ONE CALL:'
''
'      BOARD←GEN BOARD'
∇
∇RUN N;G
G←0
LOOP:'GENERATION ';G
BOARD
→0×⍳G≥N
BOARD←GEN BOARD
G←G+1
→LOOP
∇
