⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!SOURCE sw-apl -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 22.53.10 09/17/26
⍝!LINK 16807
)WSID RACE
)ORIGIN 1
)DIGITS 10
)WIDTH 120
HORSES←5 7⍴'LUCKY  THUNDERSHADOW COMET  BLAZE  '
∇DESCRIBE
'RACE -- A HORSE RACE IN PURE APL\360.'
''
'   RACE       RUN A RACE. FIVE HORSES, A RANDOM STEP EACH ROUND.'
'   SHOW       PRINT THE TRACK AS IT STANDS.'
'   HORSES     A 5 BY 7 CHARACTER MATRIX OF NAMES.'
''
'TYPE HOWRACE FOR WHAT IT DEMONSTRATES.'
∇
∇HOWRACE
'THIS WORKSPACE IS HERE TO BE READ AS MUCH AS RUN. IT USES'
'ONLY WHAT APL\360 HAS:'
''
'   A CHARACTER MATRIX FOR THE NAMES, INDEXED BY ROW.'
'   MIXED OUTPUT: TEXT AND NUMBERS JOINED WITH SEMICOLONS.'
'   THE CONDITIONAL BRANCH IDIOM →LABEL×⍳CONDITION, WHICH'
'   BRANCHES WHEN THE CONDITION HOLDS AND FALLS THROUGH WHEN'
'   IT DOES NOT.'
'   DYNAMIC SCOPING: SHOW READS POS, WHICH RACE MADE LOCAL.'
''
'THERE IS NO FORMAT, NO EXECUTE AND NO DELAY: NONE OF THEM'
'IS APL\360.'
∇
∇RACE;POS;ROUND
POS←5⍴0
ROUND←0
'THE RACE IS ON!'
LOOP:ROUND←ROUND+1
'--- ROUND ';ROUND;' ---'
POS←POS+?5⍴3
SHOW
→LOOP×⍳~∨/POS≥15
'WINNER: ',HORSES[(POS=⌈/POS)⍳1;]
∇
∇SHOW;I
I←1
N:HORSES[I;],'│',(POS[I]⍴'░'),'▓'
I←I+1
→N×⍳I≤5
∇
