[package]
name = "apl-saved"
description = "sw-apl saved half of a workspace: symbol table, activation stack, settings"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-ast = { path = "../../../parse/crates/apl-ast" }
apl-console = { path = "../apl-console" }
apl-value = { path = "../../../value/crates/apl-value" }
apl-prims = { path = "../../../prims/crates/apl-prims" }
apl-space = { path = "../apl-space" }

[lints]
workspace = true
