[package]
name = "apl-ast"
description = "sw-apl abstract syntax tree types"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-value = { path = "../../../value/crates/apl-value" }

[lints]
workspace = true
