[package]
name = "apl-prims-scalar"
description = "sw-apl scalar primitive functions with scalar extension"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-attn = { path = "../../../value/crates/apl-attn" }
apl-scalar-arith = { path = "../apl-scalar-arith" }
apl-scalar-circ = { path = "../apl-scalar-circ" }
apl-scalar-logic = { path = "../apl-scalar-logic" }
apl-value = { path = "../../../value/crates/apl-value" }

[lints]
workspace = true
