[package]
name = "apl-prims-scalar"
description = "sw-apl scalar primitive functions with scalar extension"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
apl-value = { path = "../../../value/crates/apl-value" }

[lints]
workspace = true
